import Head from "next/head";

export default function PageHeader({ title }) {
  return (
    <Head>
      <title>Bluegym - {title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
